# Configuration file for the classifier
---

# Classifier parameters
classifier:
  # the classifier to train; must exist in classifier_map in train.py
  name: "resnet50"

# ResNet18 parameters
resnet50:
  # whether to use pretrained ImageNet weights; this should be false since we are training from scratch
  pretrain: False

  # Removes whether to remove the MLP; this should be false since we are doing classification
  remove_top: False