# Base config file which stores the default parameters which apply to all model configurations
---

# Whether to run in development/debugging mode; this only uses a few samples in in the train/val dataset
# to quickly run the code as well as sets num_workers=0
dev_mode: False

# Base directory for output files; do not change this 
output_dir: "output/test"

# Experiment name; this will be used for the output directory; use "development" when developing
exp_name: "development"

# Name of dataset; must be one of the names in the dataset_map dict
dataset_name: "CocoDetection"

# Whether to plot the predicted bounding boxes on the test set; if False only the AP scores are shown
plot_detections: True

# Parameters for the dataset class
dataset:

  # Path to the root of the dataset
  root: "/mnt/d/Datasets/coco" # windows path

  # Number of CPU processes the next sample in the dataset; use 0 to only use the main process
  num_workers: 4

test:

  batch_size: 4

  # Abs path of checkpoint file (.pt) to evaluate on; 
  checkpoint_path: "/home/bselee/programming/detectors/output/train/development/2024_12_12-09_25_42_PM/checkpoints/best_mAP_0-78.pt" #"/home/bselee/programming/detectors/output/train/development/2024_11_20-05_28_25_PM/checkpoint0130.pt"

validation:
  batch_size: 4

# GPU parameters
cuda:

  # List of GPU devices to use
  gpus: [0]


# Reproducibility information
reproducibility:
  seed: 42
